### ISSUE TITLE
Support for rendering nested stacks

### ISSUE THREAD

**Issue by aaronwalker** [cfndsl/cfndsl#118]
nested stacks for example

master.rb

``` ruby
CloudFormation {
....
  Resource("VPCStack") {
    Type 'AWS::CloudFormation::Stack'
    Property('TemplateURL', "https://s3-ap-southeast-2.amazonaws.com/#{sourceBucket}/cloudformation/#{cf_version}/vpc.json" )
    Property('TimeoutInMinutes', 5)
    Property('Parameters',{
      EnvironmentType: Ref('EnvironmentType'),
      EnvironmentName: Ref('EnvironmentName')
    })

  Resource("DatabaseStack") {
    Type 'AWS::CloudFormation::Stack'
    DependsOn('VPCStack')
    Property('TemplateURL', "https://s3-ap-southeast-2.amazonaws.com/#{sourceBucket}/cloudformation/#{cf_version}/database.json" )
    Property('TimeoutInMinutes', 5)
    Property('Parameters',{
      EnvironmentType: Ref('EnvironmentType'),
      EnvironmentName: Ref('EnvironmentName'),
      RDSSnapshotID: Ref('RDSSnapshotID'),
      VPC: FnGetAtt('VPCStack', 'Outputs.VPCId'),
      RouteTablePrivateA: FnGetAtt('VPCStack', 'Outputs.RouteTablePrivateA'),
      RouteTablePrivateB: FnGetAtt('VPCStack', 'Outputs.RouteTablePrivateB')
    })
  }
.....
}
```

And we would have a corresponding cfndsl template per nested and more often that not called the sample name as the filename is the TemplateURL property. In the example above we would have a vpc.rb and database.rb

Right now we need to call cfndsl for each template not a huge deal but if we could combine this into a single cfndsl execution it would be possible to do output parameter validation. Also by combining them into a single execution we could do some calculation in one nested stack that could be used in another.

For example we calculate subnet offsets in the vpc template and then use those calculated values in the database template with out having to use cloudformation output parameters to pass essentially something that is static.

ideally I'd just like to call cfndl passing my master template and have it render all of the nested stacks and validate all of the input/output parameters from each parent and child

@stevenjack Thoughts????

**Comment by lwoggardner** [comment]
@gergnz - I think this can be achieved with current rake task and cfndsl executable.  ie common external config objects and including code the master and nested stacks can be generated in one step.
