### ISSUE TITLE
Deprecate OS Heat

### ISSUE THREAD

**Issue by gergnz** [cfndsl/cfndsl#226]
I have no idea how many people use this feature but would like to hear from those who do.

If there is no response, I'd be keen to deprecate OS Heat and focus our efforts purely on Cloudformation support.

Thoughts?

**Comment by kornypoet** [comment]
This would allow us to clean up the repo quite a bit. From personal experience I know Heat only implements a subset of Cloudformation functionality. We are already chasing the elusive compatibility of AWS as it is with our `types.yaml` file. I'm in favor of removing it. Perhaps making it a separate gem? That could be involved. I would let the discussion stick around for a while before making any changes though.

**Comment by johnf** [comment]
I'd advocate for deprecating as well, mainly because of my work on #49. If we do want to go ahead with that approach then the OS Heat code will be totally different or we'd need to convert it into the eclipse style for import.

**Comment by pvdvreede** [comment]
I only use cfndsl for Cloudformation, so would also be in favour of removing Heat so that we can focus efforts and make cfndsl do the one thing really well.

**Comment by kidbrax** [comment]
What is OS Heat?

**Comment by kornypoet** [comment]
https://wiki.openstack.org/wiki/Heat

**Comment by kidbrax** [comment]
Ah, thanks.  I would vote for deprecating and focusing on CF

**Comment by eric-tucker** [comment]
My two cents: don't try to be Terraform.  It tries to be cloud agnostic and sufferers from feature lag as a result.

**Comment by stevenjack** [comment]
Certainly agree that the OS Heat support whilst potentially useful to a small subset of the `cfndsl` users overcomplicates and makes improving the current codebase harder than it should be..

**Comment by johnf** [comment]
I would be for deprecating as well. If Amazon end up providing a schema and I continue my work in https://github.com/johnf/cfndsl/tree/new_types then keeping OS Heat would effectively mean maintaing two totally separate code bases.

**Comment by kornypoet** [comment]
Moving to stevenjack/cfndsl#257

**Comment by gergnz** [comment]
This has been removed in 1.0.0.pre branch - https://github.com/cfndsl/cfndsl/commit/be6848474561bbe3f87f8f0c45ca10f07d98964f
Closing
