### ISSUE TITLE
Clarify Functions

### ISSUE THREAD

**Issue by kornypoet** [cfndsl/cfndsl#232]
While debugging stevenjack/cfndsl#231, I noticed the functions in `lib/cfndsl/jsonable.rb` weren't all equal in terms of validation, testing and documentation. I think they could be split out into their own class, some cleanup and consolidation could be done, expanding the tests in `spec/cfndsl_spec.rb`, etc. I would be okay taking this on.

**Comment by lwoggardner** [comment]
I think we covered whatever was left for this in the 1.x work with further validation of functions.
