### ISSUE TITLE
Support for Fn::EachMemberEquals, Fn::EachMemberIn, Fn::RefAll, Fn::ValueOf , Fn::ValueOfAll 

### ISSUE THREAD

**Issue by cmaxwellau** [cfndsl/cfndsl#250]
As described at http://docs.aws.amazon.com/servicecatalog/latest/adminguide/intrinsic-function-reference-rules.html

Fn::EachMemberEquals - Returns true if a specified string matches all values in a list of strings.

Fn::EachMemberIn - Returns true if each member in a list of strings matches at least one value in a second list of strings.

Fn::RefAll - Returns all values for a specified parameter type.

Fn::ValueOf -Returns an attribute value or list of values for a specific parameter and attribute.

Fn::ValueOfAll - Returns a list of all attribute values for a given parameter type and attribute.

ValueOf and ValueOfAll support AWS::EC2::VPC::Id, AWS::EC2::Subnet::Id and AWS::EC2::SecurityGroup::Id resource types

ValueOfAll cannot have other functions inside it

**Comment by cmaxwellau** [comment]
#417 will resolve this

**Comment by lwoggardner** [comment]
Was this resolved by #417
