### ISSUE TITLE
Direct Ruby Interface?

### ISSUE THREAD

**Issue by suan** [cfndsl/cfndsl#255]
We're using cfndsl in an automated fashion from a Ruby project and it'd be nice if there was an officially supported direct-Ruby interface to invoke cfndsl, rather than have to shell out - looks like everything is pretty well-packaged in `.eval_file_with_extras`, but one still has to first put together the default params...

**Comment by kornypoet** [comment]
This is a good request. It will take some refactoring to get there, but it can (and should, I think) get done.

**Comment by kornypoet** [comment]
Moving to stevenjack/cfndsl#257

**Comment by pchaganti** [comment]
👍

**Comment by ampedandwired** [comment]
I would also find this very useful. In my [Bora](https://github.com/ampedandwired/bora) project, I'm invoking cfndsl directly from Ruby [like this](https://github.com/ampedandwired/bora/blob/16449b959309eb1fef701a479eb15cc3472449d2/lib/bora/stack.rb#L230). It would be much cleaner if it wasn't necessary to create a file with all the params first though.

**Comment by lwoggardner** [comment]
So late to this issue but I have the following helper for using Cfndsl direct from ruby.

```ruby
module CfnDslHelper

  # Include all the fun JSONABLE stuff and Fn* functions
  include CfnDsl::Functions

  def create_model(description = nil,&block)
    model = CfnDsl::CloudFormationTemplate.new
    model.declare { Description description } if description
    model.declare(&block) if block_given?
    model
  end
end
```
Sample usage
```ruby
class Builder
   include CfnDslHelper

   def build_model()
      model = create_model('ANewTemplate') do 
          Parameter('AParam')  do
             Type 'String'
          end
      end
   end

   # models can be passed around to other methods/classes
   def add_instance(model)
      this = self  # declare block is eval for the model instance so need to keep a reference
      model.declare do
         EC2_Instance(:myInstance) do
            InstanceType this.instance_type
        end
     end
  end

  def generate(model)
     model.to_json  # or JSON.pretty_generate(model) for human readable version
  end
end
```

**Comment by gergnz** [comment]
Thanks @lwoggardner. Would you be interested in raising a PR for this?

**Comment by gergnz** [comment]
@lwoggardner are you happy this is all wrapped up?

**Comment by lwoggardner** [comment]
Yes
