### ISSUE TITLE
1.0.0 Release Planning

### ISSUE THREAD

**Issue by kornypoet** [cfndsl/cfndsl#257]
This thread is intended to collect and organize all of the ideas and changes leading up to and including the `1.0.0` release of `cfndsl`.

All work will take place on the `1.0.0.pre` branch following the current collaboration practices.

There will be a living document in that branch detailing out the steps necessary and those already taken on our way to release. For now that will be `CHANGELOG.md`

**Comment by gergnz** [comment]
Remove deprecation warnings:
* Add tag
* external parameters

**Comment by gergnz** [comment]
@kornypoet where are we at with this do you think?

**Comment by kornypoet** [comment]
There have been quite a few changes made to `master` that need to get applied to the `1.0.0.pre` branch. I haven't made a lot of progress in a while. I hope to get back into the repo soon.

**Comment by gergnz** [comment]
@kornypoet please see #361

**Comment by gergnz** [comment]
@kornypoet with #361 merged, I think we are all up to date, and have covered everything in our wish list?  Thoughts on pushing this out?

**Comment by kornypoet** [comment]
I am good with us releasing the changes you made recently, but I don't know if it's truly a 1.0 release. Some of the things I think are still outstanding are:

* Direct Ruby Interface/API
* Cleaner method definition from the resource spec
* Eliminate the `eval` and `binding()` uses entirely
* Some other rough edges

The top three are pretty important and change a lot of the internal code. There's also the two cfndsl addons (lego and cfn2dsl) that are sorta wedged in there, rather than having proper places within the codebase.

**Comment by gergnz** [comment]
Hi All,

I'm planning on releasing what we have on or about the 4 March 2019.

If there are big issues with this please let me know.

Thanks,
Greg.

/cc @lwoggardner @aaronwalker

**Comment by gergnz** [comment]
@lwoggardner have you experienced any issues with `1.0.0.pre.1`?

I've run a test suite across 43 known good templates.

I have a few more templates that I'll run this against as a comparison, plus a few more items to wrap up before releasing.

**Comment by gergnz** [comment]
I've run 1.0.0.pre over 167 templates from https://github.com/neillturner/cfndsl_examples (fixes here: https://github.com/gergnz/cfndsl_examples/tree/cfndsltests)

**Comment by lwoggardner** [comment]
I ran our internal system tests against 1.0.0pre successfully.
