### ISSUE TITLE
CFN schema

### ISSUE THREAD

**Issue by domdivakaruni** [cfndsl/cfndsl#264]
The AWS CloudFormation team is looking to publish and maintain a machine readable schema. I imagine this will be helpful for you. :) We're thinking of a couple formats for the schema, see attached and let me know which one you prefer. Thx!
[json-schema style.zip](https://github.com/stevenjack/cfndsl/files/572375/json-schema.style.zip)
[FreeStyle.zip](https://github.com/stevenjack/cfndsl/files/572376/FreeStyle.zip)

**Comment by ebekker** [comment]
I agree with @kornypoet that the FreeStyle is more human-digestible, however, for me, I intend to feed this into a code generator as per my initial comment (https://github.com/stevenjack/cfndsl/issues/75#issuecomment-205860069), so I could work with either style for my purposes.

**Comment by ebekker** [comment]
@domdivakaruni -- once a format is finalized, do you intend to publish it on GitHub?  It would be nice if it was a medium that supported crowd-sourcing for any corrections.

**Comment by allinwonder** [comment]
@domdivakaruni by reviewing both formats, I prefer the `json-schema style`, as the complex properties have explicit links to type definitions, this means the downstream application can go deeper into property definitions and provide more accurate and comprehensive code generation.

**Comment by elmobp** [comment]
+1 for the json_schema style

**Comment by johnf** [comment]
I think it would be valuable to have both.

For the purposes of this project I think that the ```free style``` format is going to be much easier to deal with and provides the information required while being quite easy to work with.

On the other hand if I want to actually validate the JSON output then ```json-schema style``` will probably be more useful, since I assume I can throw it at some standard tools to validate my JSON output is correct.

**Comment by elmobp** [comment]
We have schema!!! https://aws.amazon.com/about-aws/whats-new/2016/11/aws-cloudformation-introduces-resource-specifications-cross-stack-reference-update-and-coverage-updates/

**Comment by domdivakaruni** [comment]
:)

**Comment by ebekker** [comment]
@domdivakaruni, thanks for this great addition!

Can you say whether the file links published on the CFN Resource Specification [page](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-resource-specification.html) are *stable* -- that is, will the links there always point to the latest version of their respective specs, or are the links going to change as the specs are updated?  They look like they're randomly generated out of CloudFront, so I suspect not?

The reason I'm asking is that I would like to be able to automagically pull the specs on a recurring basis to detect if anything has been changed so that I know if they need to be re-processed?

**Comment by allinwonder** [comment]
@domdivakaruni the schemas are distributed in regional bases, to automate and simplify tracking the changes in each region, would you consider to create an SNS topic to allow public subscribers (email and lambda) to receive notification of schema updates?

**Comment by ebekker** [comment]
@allinwonder, it's not quite a notification, but I've setup a recurring task to test for changes in the Resource Specification (only against the `US East (N. Virginia)` region) and when a change is detected, the new version is captured here:  https://github.com/ezshield/posh-awscfn/tree/master/pub

**Comment by ebekker** [comment]
Additionally, I've also setup a task to generate a documentation summary by pulling the first paragraph of each Property Type and Resource Type and the first paragraph of each of their child properties from the Documentation URL out of the Resource Spec.

This documentation summary can also be found [here](https://github.com/ezshield/posh-awscfn/tree/master/pub) as this file (it's a couple MiBs):  https://github.com/ezshield/posh-awscfn/blob/master/pub/CfnResSpecDocs.json

**Comment by ebekker** [comment]
@domdivakaruni -- there is some useful information that used to be included in the v1 Schema file, but is not documented in the new Resource Specification format, such as the `allowed-values` list.

For example, in the v1 Schema, the resource `AWS::AutoScaling::AutoScalingGroup` had several properties and sub-properties that each had a fixed list of allowed values:
* `AvailabilityZones` : *(all the legal AZs)*
* `HealthCheckType` : `EC2`, `ELB`
* `NotificationConfiguration.NotificationTypes` : *(several pre-defined constant strings)* 

This is just an example, and almost all of the resources had several *common* properties that had a fixed list of allowed values, such as `DeletionPolicy`.

Is there a plan to incorporate this into the Specification?  It seems like the new spec would be a step back without these lists to support automated tool validation?

**Comment by elmobp** [comment]
@ebekker heh I was going to scrape the docs to generate it as well! nice work

**Comment by domdivakaruni** [comment]
@ebekker @allinwonder we will soon have a way to subscribe to notifications or events for updates, as well as strongly typed values for resource properties ( and sub props). Some of the allowed values will be captured in the next releases but many of the ones you mentioned we rely on the down stream service to validate/maintain hence wont be available thru our specifications.

**Comment by ebekker** [comment]
@domdivakaruni -- I know some of your allowed values are not "strongly typed" for example the availability zones which are somewhat fluid based on a particular user's account.  Say for example, you're preparing to release a new Region or AZ, and some accounts have access to it, while others don't.

So I wonder -- would it be possibly to provide *strict allowed values* vs. *relaxed suggested values*.  The point being, it provides a way for tooling to help a user define the templates *in the moment*.  The suggested values could be somehow suggested to a user without enforcing strict adherence to an allowed values list.

**Comment by domdivakaruni** [comment]
@ebekker, great suggestion! Let us look into it.

**Comment by kornypoet** [comment]
@domdivakaruni I've found a few errors and inconsistencies in the published schema. Where should I report these?
