### ISSUE TITLE
Integrate CF Resource Specification

### ISSUE THREAD

**Issue by bsideup** [cfndsl/cfndsl#276]
Hi!

Starting from yesterday, AWS now publishes CF spec in JSON:
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-resource-specification.html

Would be cool to integrate it, especially dynamically, so one don't have to update cfndsl to get the new resource definitions

**Comment by kornypoet** [comment]
@gergnz @johnf I am going to take a stab at this over the holiday weekend. My approach will be as follows:

* Add a command to the `cfndsl` executable to download the latest schema
* Store the schema locally at `~/.cfndsl/resource_specification.json`
* Allow a command-line flag to override the above location for both download, and template evaluation
* Invoke the download by default if the specification file is not found (to ensure any upgraded users have immediate functionality
* Use no outside dependencies (ie, no additional gems, or curl or wget)
* Only implement existing behavior at this time. We can expand the functionality later.
* I would like to release this first, before the major refactor for `1.0.0`

If you guys have any issues with this, let me know. Cheers.

**Comment by allinwonder** [comment]
@kornypoet I am not sure the following point is a good approach or not

   `Invoke the download by default if the specification file is not found (to ensure any upgraded users have immediate functionality`

My thinking is rather than download by default, the tool should use shipped schemas by default because we can have tests against the default schemas, so the quality of the integration can be assured. If the user wants to override the shipped schema, the tool provides option to do that

another point I want to add is, the schemas are regional bases, so either we stick to use the same region, or include them all and let the user select which region they are developing against.

**Comment by kornypoet** [comment]
As developers working on cfndsl, one of the things we wanted to avoid was having to constantly update the schema in the repo. If we include a base schema with cfndsl, it's only a matter of time before it's outdated. From a user experience, it would be bad if someone were to newly install `cfndsl` only to find it needs to be updated immediately. The other contributors can sound in, but I personally don't want to continue to maintain a schema in the repo now that AWS has published one.

From a user experience standpoint, the more that happens for you (the way you expect) the better. If you gem install `cfndsl`, I want it to just work. It's customizable if you don't like the default.

As far as the regions go, I think we should just stick to us-east-1 and if you need a different one, you can update it yourself. At some point, we can add a flag to select a region, but maintaining a map of all regions (and expanding as AWS adds more), while constantly updating urls seems like a nightmare.

**Comment by elmobp** [comment]
@kornypoet we could add a region flag to cli?

**Comment by cmaxwellau** [comment]
How about parsing the AWS_REGION from the env in the same way that the AWS
cli does, but having ~/.cfndsl/confg instead of the aws cli config.

Also I agree with having the gem work 'out of the box' for users. Perhaps
ship with the multi region schema AND allow the gem to update it's local
version as well.

My $0.02

**Comment by kornypoet** [comment]
@elmobp We could add a region flag, but see my above concern about maintaining a map of regions -> url. I'm surprised that there is this much concern as there is hardly any variance between regions, and I imagine that having the superset of resources that I presume using us-east-1 will provide would not create any problems in other regions. 
Reading from aws configuration is the best way to guarantee no surprises, however, people configure these differently, using AWS_REGION or ~/.aws/config, or even profiles. The proper way to implement reading from existing configuration would be to use the ruby aws sdk, but we've managed to keep from adding any external dependencies (which I think is a plus).

**Comment by elmobp** [comment]
*cough* EFS ;) or w just write the region handler directly in? and not rely on the sdk port the aws region handler to cfndsl..

**Comment by gergnz** [comment]
I don't want regions at all. We develop our infracode to work where ever. I didn't actually consider that it'd be so region specific (I understand why, but the interesting point is there isn't 11 versions of the docs, one for each region. Surely it would be better to have a field in the schema with support regions?). We as humans make the decision to go with or without a specific service in a full stack if it's not in a specific region. I just want the super set (hopefully that's us-east-1).
@kornypoet, I'd also draw your attention to the work that @elmobp has been putting in #277. Want to avoid rework.

**Comment by kornypoet** [comment]
@gergnz noted. I don't see much overlap in the way we want to implement the schema and the work @elmobp has done to integrate cfnlego.
