### ISSUE TITLE
One cfndsl file => multiple Cloudformation templates

### ISSUE THREAD

**Issue by josh-wrale** [cfndsl/cfndsl#29]
Hello again.

For large templates, the normal size limit for a single Cloudformation template is 51200 bytes.  

If someone wants to create a large, layered and highly available VPC, creating a Ruby loop in cfndsl makes quick work of generating the many subnets, routes, routetables, and on.  Such a deployment if attempted with a monolithic Cloudformation template quickly expands to an illegally large size.

The next issue comes when you consider the limit of 10 outputs per template.  The  advertised answer to having too large a template is to layer templates by using parameters and outputs.  The stack I'm seeking to build has approximately ten tiers (layers of VPC subnets) striped across three availability zones.  Creating such a deployment with layers quickly runs against the output limit, especially when one tries to pass the metadata for so many subnets down to nested templates.

My imagined solution is to take a very granular approach while using parametrization, in a cfndsl-generated layering structure.  This method would use the same foundational Ruby loops, arrays and hashes as before, in a monolithic cfndsl file to output multiple interlocking Cloudformation templates as a single JSON stream.  In this way, one cfndsl Ruby file would output one long JSON file having individual self-contained Cloudformation templates throughout.  A simple post-processing function would then be implemented to split the many Cloudformation templates into discrete files.

I was able to create two Cloudformation blocks inside of my cfndsl template successfully.  However, piping it to json_pp failed.  I think an extra JSON wrapper level is required for this to work without error. 

The other obvious option is for me to generate discrete cfndsl files to bring about the layered structure.  Without some shared arrays and such, the hand-coding of each template would all but negate one of the main reasons I chose cfndsl in the first place: very powerful for each loops.

I'll stop rambling now.  Please let me know if any of this makes sense.

Thanks,
Joshua

**Comment by yumpy** [comment]
I'm having a similar challenge having breached the 51200 byte limit and splitting a template into several layers. I've decided not to nest the stacks but to treat them as separate layers.
