### ISSUE TITLE
Validate Resource Names

### ISSUE THREAD

**Issue by kornypoet** [cfndsl/cfndsl#343]
Got this the other day when dynamically creating resources:

```
Error invoking create_stack: Template format error: Resource name foo_private is non alphanumeric.
```

This is an AWS restriction that seems easy enough to implement in `cfndsl`, and provides faster feedback on malformed templates.

**Comment by cmaxwellau** [comment]
@kornypoet I've written a wrapper for cfndsl and cfn_nag that picks up things like this, especially null values :)

[https://github.com/cmaxwellau/cfndsl-pipeline](https://github.com/cmaxwellau/cfndsl-pipeline)

**Comment by gergnz** [comment]
see #257
