### ISSUE TITLE
Schedule Event Rule creates an invalid JSON on FnGetAtt Arn.

### ISSUE THREAD

**Issue by dsmithfv** [cfndsl/cfndsl#344]
I'm trying to use the ECS Schedule Task service.  Everything works except for specifying the Arn.  According to AWS documentation you must use FnGetAtt to reference the Cluster ARN and Role.

Here is my input:

```
Events_Rule "NewTask#{event_item}" do
      Name Ref "Name#{event_item}"
      Description Ref "Description#{event_item}"
      State Ref "State#{event_item}"
      ScheduleExpression Ref "ScheduleExpression#{event_item}"
      Targets [
      {
        Arn: FnGetAtt(Ref("TargetArn#{event_item}"), "Arn"),
        EcsParameters: {
          TaskCount: Ref("TaskCount#{event_item}"),
          TaskDefinitionArn: Ref("TaskDefinitionArn#{event_item}")
        },
        Id: Ref("TaskId#{event_item}"),
        RoleArn: FnGetAtt(Ref("RoleArn#{event_item}"), "RoleArn")
      }
  ]
end
```
This line expands improperly when I run cfndsl:

```
 Arn: FnGetAtt(Ref("TargetArn#{event_item}"), "Arn"),
```

Json output for the Arn:

```
           "Arn": {
              "Fn::GetAtt": [
                {
                  "Ref": "TargetArnWorkerProcessRecordCleanUp"
                },
                "Arn"
              ]
            },
```

As you can see "Arn" gets put outside the parentheses.  Any thoughts on why this happens?  Could it be the arguments cfndsl expects to see?

AWS Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-events-rule-target.html

**Comment by gergnz** [comment]
Hi @dsmithfv,

I'm not sure where on that page it uses a nested Ref within a Fn:GetAtt. Sorry if I've missed it.

I think you need to remove the Ref, and instead, just refer to the logical ID of your resource you wish to target.

e.g. I think something like this:
```ruby
Lambda_Function "MyLambdaFucntion" do
...
end
Events_Rule "MyEventRule" do
...
Targets [
{
   Arn: FnGetAtt("MyLambdaFunction", "Arn"),
...
end
```
See also:
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-getatt.html
and
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-ref.html
