### ISSUE TITLE
Transfer repo ownership

### ISSUE THREAD

**Issue by stevenjack** [cfndsl/cfndsl#352]
Hey guys, I'd like to transfer the repo over to one of you as I haven't worked on it for quite some time now and you guys have done such great work it's only fair that one of you should take ownership 👍.

Let me know who you think's best @gergnz @kornypoet!

**Comment by gergnz** [comment]
Thanks @stevenjack.

Not sure what you mean by ownership, but if you mean transition the repo to one of us, maybe we should setup an org/user that is cfndsl?

e.g. I just created: https://github.com/cfndsl

If you guys are happy with that, I'll send invites.

**Comment by stevenjack** [comment]
@gergnz yep that's what I meant, yea I'm happy to transfer it over to an org.

**Comment by stevenjack** [comment]
@gergnz I've transferred the repo over to the organisation 👌

**Comment by gergnz** [comment]
@stevenjack what do we need to do with travis?

**Comment by stevenjack** [comment]
@gergnz I've checked travis and running the builds as expected under the new org:

![image](https://user-images.githubusercontent.com/527874/32485334-00724a82-c39b-11e7-9d24-8614db91b8f4.png)

In terms of ruby gems, the encrypted key that travis uses doesn't need to change and the links from ruby gems back to the documentation redirect to the new org.

With Gitter, I'm not sure if it follows the redirect - the existing chat seems to still be available:

https://gitter.im/stevenjack/cfndsl

however it seems to be quite sporadically used, could just post a message in there directing people to leave issues here then remove it from the README?

**Comment by gergnz** [comment]
Gitter is very quiet. Winding it up might be a good idea. Thanks for looking into rubygems and travis.

**Comment by gergnz** [comment]
```Skipping a deployment with the rubygems provider because this repo's name does not match one specified in .travis.yml's deploy.on.repo: stevenjack/cfndsl```

Updating .travis.yml and gemspec
