### ISSUE TITLE
Code Deploy - missing settings

### ISSUE THREAD

**Issue by devops-dude** [cfndsl/cfndsl#358]
I'm trying to define my "LoadBalancerInfo" using "AWS::CodeDeploy::DeploymentGroup":.  I get an error that it is an undefined method.  I tried updating your types.yaml file, but I still get an undefined method error.  I noticed from the AWS documentation that there are a few settings missing from CodeDeploy::DeploymentGroup...

```
"AlarmConfiguration" : AlarmConfiguration,
"AutoRollbackConfiguration" : AutoRollbackConfiguration,
"DeploymentStyle" : DeploymentStyle,
"LoadBalancerInfo" : LoadBalancerInfo,
"TriggerConfigurations" : [ TriggerConfig, ... ]
```

AWS docs - http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codedeploy-deploymentgroup.html#cfn-codedeploy-deploymentgroup-loadbalancerinfo

I'm not sure what I need to modify beyond the types.yaml, but I can fix and provide a pull request if you point me in the right direction.  Thanks!

**Comment by gergnz** [comment]
Hi @devops-dude,

can I confirm what version of the cloudformation specification file you have and the version of cfndsl?

**Comment by kidbrax** [comment]
I am having the same issue with LifecyclePolicy missing from ECR_Repository.  What is the best process for submitting these requests or better yet fixing them ourselves.  Since, it appears updating the yaml is not the correct method.

cfndsl 0.16.1

**Comment by gergnz** [comment]
HI @kidbrax 

If you have the latest specification file from AWS and it is still not in there, the best way is to raise a support case with AWS and request that the specification file get updated to reflect current cloudformation capability.

To update the spec file you can run `cfndsl -u`. I'm currently sitting on version 1.12.0:

```
"ResourceSpecificationVersion": "1.12.0"
```

**Comment by kidbrax** [comment]
Yes, i just updated it and it worked, thanks.  Keep forgetting about doing that.  I would recommend adding a switch to the cli to spit out the spec version though
