### ISSUE TITLE
Can't get -D option to work

### ISSUE THREAD

**Issue by jsywulak** [cfndsl/cfndsl#360]
Hi there--

I'm trying to leverage the -D option of CFNDSL and I'm running into an issue.  Using the example in the readme:

    CloudFormation do
      description = external_parameters.fetch(:description, 'default description')
      machines = external_parameters.fetch(:machines, 1).to_i

      Description description

      (1..machines).each do |i|
        name = "machine#{i}"
        EC2_Instance(name) do
          ImageId 'ami-12345678'
          Type 't1.micro'
        end
      end
    end

With no options, this works fine: `cfndsl sample/t1.rb` produces a template.

However, when I use the `-D` syntax from the readme, I get issues (edited for brevity):

      $  cfndsl sample/t1.rb -D 'description=3 machine cluster' -D 'machines=3'
      ...
      /Local/Users/jonny/.rvm/gems/ruby-2.4.0/gems/cfndsl-0.15.2/lib/cfndsl.rb:80:in `eval': raw code:1: syntax error, unexpected tIDENTIFIER, expecting end-of-input (SyntaxError)
      description=3 machine cluster
      ...

It appears that it's trying to interpret `3 machine cluster` as a raw ruby code, which is invalid. I'm seeing similar behavior even with strings with no whitespace. 

My first reaction was to enclose it in quotes, which almost works: `cfndsl sample/t1.rb -D 'description="3 machine cluster"' -D 'machines=3'`  This will produce a cfn template, but...

    {
      "AWSTemplateFormatVersion": "2010-09-09",
      "Description": "\"3 machine cluster\"",
      "Resources": {

The quotes remained as part of the value, which is not what I was going for.

The workaround is to use quotes, and then just strip them out of the value at runtime, but that's annoying. Is there something I'm doing wrong here or is this a bug in how the code is interpreted? 

Thanks!!

**Comment by kornypoet** [comment]
Try also using the `-b` option to disable bindings.

```
bin/cfndsl sample/t1.rb -p -b -D 'description=foo bar baz'
{
  "AWSTemplateFormatVersion": "2010-09-09",
  "Description": "foo bar baz",
  "Resources": {
    "machine1": {
      "Properties": {
        "ImageId": "ami-12345678"
      },
      "Type": "AWS::EC2::Instance"
    }
  }
}
```

Long story short, the code used to `eval` arguments passed to `-D` and this behavior has been deprecated as it was unsafe and often unpredictable. The recommended approach is to use a variable file with `-y/-j` or manipulate the `CfnDsl::ExternalParameters.defaults` yourself in Ruby code ahead of time.
