### ISSUE TITLE
Composing and merging CfnDsl templates

### ISSUE THREAD

**Issue by ralovely** [cfndsl/cfndsl#375]
Hi.

First, thank you for this gem.
It takes CloudFormation to yet another level.

Question:

For larger templates, I'd like to "compose" them, a bit like CloudFormation templates can be nested.
Maybe by merging two `CloudFormation` objects, or maybe by appending.
Pseudo code to illustrate:

```ruby
tpl_a = CloudFormation do
  Description 'Do some stuff'
  EC2_Instance(:MyInstance) {
    ImageId "ami-12345678"
  }
end

tpl_b = CloudFormation do
  EC2_Instance(:MyOtherInstance) {
    ImageId "ami-12345678"
  }
  # ...
end

tpl_c = tpl_a + tpl_b 
```

and/or

```ruby
tpl = CloudFormation do
  Description 'Do some stuff'
  EC2_Instance(:MyInstance) {
    ImageId "ami-12345678"
  }
end

another_resource =  EC2_Instance(:MyOtherInstance) {
                        ImageId "ami-12345678"
                      }

tpl << another _resource
```

Of course, the merging version would pose quite a few issues, mainly with conflicting resources and stanza. This could be offloaded to the user, just erroring.

Is there a creative way to work around this with the current release?
Is it something that would make sense to implement?
How would you go about it?

Thank you.

**Comment by gergnz** [comment]
Hi @ralovely,

There has been some debate about this in the past from the likes of:
@lwoggardner @johnf and @aaronwalker.

I'm not sure that anyone of their ideas have made it off their desktop or work environments into the wild yet.

I would love to see something like this also, but I haven't had the chance to sit down and work on it either sadly.

We'd happily welcome a pull-request though if you have some ideas.

**Comment by aaronwalker** [comment]
@gergnz I vaguely showed you this at some stage but we have done a bit of work on this of late

https://github.com/theonestack/cfhighlander which address some of these issues plus others. Right now it supports components as nested stacks and extend components (a form or merging templates) but we plan to support inlining as well in the near future.

Under the github org https://github.com/theonestack/ we have created a number of components as basic building blocks.

Any feedback would be much appreciated 😄

**Comment by cmaxwellau** [comment]
This would have to be done at the &block level. @ralovely how do you image using this in cli or native form?

**Comment by lwoggardner** [comment]
Feels like this can be done already through the various embedded ruby techniques discussed in the README of 1.x
