### ISSUE TITLE
Plural version of a subType Property behaves differently to Resource Property

### ISSUE THREAD

**Issue by lwoggardner** [cfndsl/cfndsl#380]
```ruby
EC2_LaunchTemplate {
  LaunchTemplateData {
     SecurityGroupIds FnSplit(...)  # doesn't work - results in "SecurityGroupIds" : [ { "Fn::Split" ... } ] 
  }
}

Autoscaling_LaunchConfiguration {
   SecurityGroupIds FnSplit(...)  # does work -> "SecurityGroupIds" : { "Fn::Split" ... }
}
```

PR to come

**Comment by lwoggardner** [comment]
This is going to require a breaking change.

Plural method for a list attribute inside a subType is treated the same as the singluar form - it always appends to the list which makes it impossible to use Ref or FnSplit as the target

Plural method for a list property of a Resource behaves differently to the singular form,  for array or hash it replaces the property, or singular values it appends.

I would propose to change the subType  behaviour to match the existing Resource behaviour.

This will break existing code that is passing an Array to the plural form of a subtype property and expecting append.  The fix would be to change code to use the singular method instead.

**Comment by gergnz** [comment]
see #257
