### ISSUE TITLE
uninitialized constant CfnDsl::AWS::Types::Map

### ISSUE THREAD

**Issue by cleblanc87** [cfndsl/cfndsl#382]
This error started this morning on 16.8 and 17.pre

**Comment by gergnz** [comment]
Looks to be a problem with `2.17.0` of the cloudformation spec

**Comment by cleblanc87** [comment]
@gergnz is there a way around this, or can you point me in the direction where changes are needed within cfndsl?

**Comment by gergnz** [comment]
Hi @cleblanc87 there is a type that needs to be added to lib/cfndsl/patches.rb to _monkey patch_ the specification. I'm currently taking a look, but not going to have a lot of time today.

**Comment by cleblanc87** [comment]
Thanks! I'll see if I can get a PR up

**Comment by aaronwalker** [comment]
@gergnz +💯 :)
