### ISSUE TITLE
Use the AWS-CDK as a source for patches

### ISSUE THREAD

**Issue by gergnz** [cfndsl/cfndsl#385]
Should we be storing patches as json and then patching the specification?

A note from @iann0036 suggests to use these https://github.com/awslabs/aws-cdk/tree/7a8ee2c5b704ba4565f5b5165ca9aea1e03ded07/packages/%40aws-cdk/cfnspec/spec-source

**Comment by PatMyron** [comment]
The CloudFormation Linter also maintains some specification patches around here:
https://github.com/aws-cloudformation/cfn-python-lint/tree/master/src/cfnlint/data/ExtendedSpecs/all

**Comment by gergnz** [comment]
see #257
