### ISSUE TITLE
ArtifactStore and ArtifactStores are not the same thing

### ISSUE THREAD

**Issue by gergnz** [cfndsl/cfndsl#389]
similar to #380 and #354 

This is actually 2 different Properties in AWS::CodePipeline::Pipeline.

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codepipeline-pipeline.html

**Comment by gergnz** [comment]
I propose that we remove pluralisation.  There are so many edge cases in Cloudformation that we could be chasing our tail a lot.

See PRs: #390 and #392

**Comment by bzivic** [comment]
@gergnz any update on this issue still present.

CodePipeline ArtifactStore in cfndsl converts to ArtifactStores in cfn, instead of just ArtifactStore.

**Comment by gergnz** [comment]
Hi @bzivic, sadly I wasn't able to work out a decent fix for this one.
I've successfully been using:
```
    ArtifactStore(
      Type: 'S3',
      Location: Ref(:bucket)
    )
```
Do you have multiple ArtifactStores you need referenced?

**Comment by gergnz** [comment]
see #257
