### ISSUE TITLE
Access to rubygems

### ISSUE THREAD

**Issue by gergnz** [cfndsl/cfndsl#391]
@howech or @stevenjack are one of you able to add me to the project in rubygems.org please?

**Comment by stevenjack** [comment]
@gergnz Sorry I must have missed this, just noticed a push to ruby gems with my API key that the travis job is still setup with. I can add you to rubygems.org, then can we then switch around the API key in `.travis.yml` to not be mine?

**Comment by gergnz** [comment]
@stevenjack my username on rubygems is gergnz. Thanks.

**Comment by stevenjack** [comment]
@gergnz You've now been added 👍
