### ISSUE TITLE
1.0.0-pre bugs in OrchestrationTemplate#validate

### ISSUE THREAD

**Issue by lwoggardner** [cfndsl/cfndsl#403]
I've been doing some work with the 1.0.0-pre branch on some complex real life templates and have found bugs in the cyclic refs checking of the new #validate method I put together for direct ruby usage.

PR to come but will likely take more than a week.

**Comment by lwoggardner** [comment]
More than a week Is apparently more than 7 months. I still plan to work on this. Probably will remove all attempts at cyclic dependency checking. I think better to leave that to the actual cloudformation validate API.

**Comment by gergnz** [comment]
see #257
