### ISSUE TITLE
latest specification issues with 0.16.2

### ISSUE THREAD

**Issue by nagliyvred** [cfndsl/cfndsl#404]
Hi cfldsl team,
It looks like the latest spec (2.24.0) doesn't work with 0.16.2. 
I am getting the following:
`
NameError: uninitialized constant CfnDsl::AWS::Types::AWSEC2SpotFleetTag
Did you mean?  CfnDsl::AWS::Types::AWSEC2NetworkAclEntryPortRange
`
Am I doing something wrong? 
Also, I am wondering if there is a way to find out what's the supported cfn spec for each given version of cfndsl? I am struggling to make the gem work with any of the relatively recent versions...

Thanks in advance!
Evgeny

**Comment by gergnz** [comment]
Hi @nagliyvred, you'll need to update cfndsl to at least 0.16.11 (I think). We've also added a feature that allows you to update to specific version of the template if you don't need newer cloudformation specification, and thus can live without updating cfndsl: `cfndsl -u 2.20.0` for example.

Hope that helps.

**Comment by nagliyvred** [comment]
Thank you @gergnz - that worked!
