### ISSUE TITLE
Warning when External Yaml/JSON files share top level namespace

### ISSUE THREAD

**Issue by cmaxwellau** [cfndsl/cfndsl#418]
I use multiple YAML files to define tag values, one global one for a customer, and one local one for the stack itself. Both share the high level namespace TagStandard, but have mergeable children.

I get the following warning:
.rvm/gems/ruby-2.4.4/gems/cfndsl-0.17.1/lib/cfndsl.rb:62: warning: already initialized constant CfnDsl::TagStandard
.rvm/gems/ruby-2.4.4/gems/cfndsl-0.17.1/lib/cfndsl.rb:62: warning: previous definition of TagStandard was here

I have a fix for this

**Comment by gergnz** [comment]
see #257
