### ISSUE TITLE
Boolean value with -D

### ISSUE THREAD

**Issue by gdlx** [cfndsl/cfndsl#429]
Defining a boolean value with `-D VARIABLE=false` results in a "false" string inside `external_parameters` instead of the boolean `false`.

The same variable provided in a Yaml file with `-y` results in a boolean value.

Is there a way to provide a boolean value with `-D` ?

**Comment by gergnz** [comment]
This is a function of `optparse` and the shell. Everything is a string.

We could look at doing something like this:
```ruby
-        params.set_param(file_parts[0],file_parts[1..-1].join("="))
+        if file_parts[1].downcase == 'true' then
+          params.set_param(file_parts[0],true)
+        elsif file_parts[1].downcase == 'false' then
+          params.set_param(file_parts[0],false)
+        else
+          params.set_param(file_parts[0],file_parts[1..-1].join("="))
+        end
``` in _lib/cfndsl.rb_

or when you read in parameters in your cfndsl block look at using something like this:
```ruby
CloudFormation do
  params = {}
  external_parameters.each_pair do |key, val|
    key = key.to_sym
    params[key] = if val.is_a?(String) && val.downcase == 'true'
                    true
                  elsif val.is_a?(String) && val.downcase == 'false'
                    false
                  else
                    val
                  end
  end
...
end
```

**Comment by gdlx** [comment]
I've done something like the second example.
But I don't think there are use cases where you could provide a true/false value and expect a string as a result so it may be nice for cfndsl to do it by default.

**Comment by gergnz** [comment]
This is a breaking change for anyone who is doing string tests for today, so I'm reluctant to make this breaking change in the 0.x.x version. I'll look at adding it to 1.x.x

**Comment by gergnz** [comment]
see #257
