### ISSUE TITLE
Possible regressions 0.17.5 -> 1.0.0

### ISSUE THREAD

**Issue by adrianmace** [cfndsl/cfndsl#442]
Hi guys,

Firstly thanks for the amazing tool. Use it every day in a number of CI pipelines!

We had previously pinned to `latest` but over the last few days we were forced to pin back to `v0.17.5` due to the release of `1.0.0` and it's instant deprecation of the `--disable-binding` flag.

I am not the original code author and am looking to refactor the code to no longer require the flag, but do not know what behaviour the flag has / can't find any examples of how to use it. **Can you please provide some brief examples so I can determine why this is currently necessary and how to remove it?**

**Comment by gergnz** [comment]
Hi @adrianmace,

The issue was raised back in #170 and then a flag was introduced in #172 and then eventually made its way into the code via #179.

We finally pulled this out in 1.0.0 as being deprecated through the late 0. series.

Ultimately it disabled unsafe behaviour. It is safe to remove the flag from pipelines or scripts if you have been setting that flag as it is now the default (in fact you can't go back to the old behaviour).

For others finding this. If you rely on using ruby bindings, you will need to adjust the approach used to included external parameters.

Hope that helps.

**Comment by adrianmace** [comment]
That does, thank you. It means that my code is failing due to some other reason and that taking `--disable-binding` out of the pipeline is only exposing the next error in a series or perhaps many. Will continue to investigate. Thanks!

**Comment by gergnz** [comment]
keep me posted as I'd like to understand any regressions please.

**Comment by adrianmace** [comment]
Renaming this issue so it doesn't seem confusing. Please see the following snippet and associated CFN outputs.

Code snippet:
```
  Parameter("InstanceSubnets") do
    Type "AWS::SSM::Parameter::Value<List<AWS::EC2::Subnet::Id>>"
  end
...
  AutoScalingGroup("Asg") do
    AvailabilityZones ["ap-southeast-2a", "ap-southeast-2b", "ap-southeast-2c"]
    VPCZoneIdentifier (
      Ref("InstanceSubnets")
    )
    LaunchConfigurationName Ref("LaunchConfig")
...
```
Cloudformation snippet:
```
INFO: [03:26:11] Asg - UPDATE_FAILED - Value of property VPCZoneIdentifier must be of type List of String
```

**Comment by gergnz** [comment]
Try changing `VPCZoneIdentifier` to be `VPCZoneIdentifiers` (pluralisation got quite a bit of overhaul)

**Comment by adrianmace** [comment]
Before I try that, I have discovered something by generating the template using both old and new versions of `cfndsl`. It looks like the new version is handling it by putting it in a list, when it's already in one, creating a list of lists.

v0.17.5
```
...
      - ap-southeast-2c
      VPCZoneIdentifier:
        Ref: InstanceSubnets
      Cooldown: 1200
...
```
vLatest
```
...
      - ap-southeast-2c
      VPCZoneIdentifier:
      - Ref: InstanceSubnets
      Cooldown: 1200
...
```

**Comment by adrianmace** [comment]
> Try changing `VPCZoneIdentifier` to be `VPCZoneIdentifiers` (pluralisation got quite a bit of overhaul)

That looks to have done it, returned the CFN template back to the correct syntax!

**Comment by adrianmace** [comment]
Happy for you to close this issue! I'll raise any more but this was definitely the cause of that particular issue. Thanks for your help!
