### ISSUE TITLE
CloudFrontOriginAccessIdentity is an undefined method

### ISSUE THREAD

**Issue by kidbrax** [cfndsl/cfndsl#448]
I am trying to add a [AWS::CloudFront::CloudFrontOriginAccessIdentity](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudfront-cloudfrontoriginaccessidentity.html) by using `CloudFrontOriginAccessIdentity` but it errors with 
```
undefined method `CloudFrontOriginAccessIdentity' for #<CfnDsl::CloudFormationTemplate:0x0000000002cae098>
```

**Comment by lwoggardner** [comment]
1.x requires fully qualified names - so ```CloudFront_CloudFrontOriginAccessIdentity```

**Comment by kidbrax** [comment]
That didn't seem to work either. `undefined method 'CloudFront_CloudFrontOriginAccessIdentity'`

**Comment by gergnz** [comment]
Hi @kidbrax,

Are you able to please post the output of:
`cfndsl --version`
`cfndsl -a`
`cfndsl -u`

And if possible a snippet of the code so I can reproduce it.
Thanks.

**Comment by kidbrax** [comment]
I updated my version of cfndsl and this worked fine.
