### ISSUE TITLE
Shorthand method of accessing resource attributes via FnSub fails reference checks

### ISSUE THREAD

**Issue by gregwork** [cfndsl/cfndsl#455]
CloudFormations `Fn::Sub` intrinsic allows for a shorthand notation when accessing resource attributes.

From the [documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-sub.html):
> If you specify resource attributes, such as ${MyInstance.PublicIp}, AWS CloudFormation returns the same values as if you used the Fn::GetAtt intrinsic function.

When using the reproduction case below with cfndsl, this shorthand form of notation causes the template build to fail with the following error:
```
CfnDsl::Error: 1 errors in template
Invalid Reference: Outputs ["output"] refer to unknown Reference eip.AllocationId
  /home/greg.work/temp/cfndsl-test/.bundle/vendor/ruby/2.6.0/gems/cfndsl-1.0.6/lib/cfndsl/orchestration_template.rb:286:in `validate'
  /home/greg.work/temp/cfndsl-test/.bundle/vendor/ruby/2.6.0/gems/cfndsl-1.0.6/lib/cfndsl/cloudformation.rb:113:in `CloudFormation'
  /home/greg.work/temp/cfndsl-test/test.rb:3:in `eval_file_with_extras'
  /home/greg.work/temp/cfndsl-test/.bundle/vendor/ruby/2.6.0/gems/cfndsl-1.0.6/lib/cfndsl/cloudformation.rb:57:in `eval'
  /home/greg.work/temp/cfndsl-test/.bundle/vendor/ruby/2.6.0/gems/cfndsl-1.0.6/lib/cfndsl/cloudformation.rb:57:in `eval_file_with_extras'
  /home/greg.work/temp/cfndsl-test/.bundle/vendor/ruby/2.6.0/gems/cfndsl-1.0.6/lib/cfndsl/runner.rb:126:in `invoke!'
  /home/greg.work/temp/cfndsl-test/.bundle/vendor/ruby/2.6.0/gems/cfndsl-1.0.6/exe/cfndsl:5:in `<top (required)>'
  /home/greg.work/temp/cfndsl-test/.bundle/vendor/ruby/2.6.0/bin/cfndsl:23:in `load'
  /home/greg.work/temp/cfndsl-test/.bundle/vendor/ruby/2.6.0/bin/cfndsl:23:in `<top (required)>'
```

Reproduction case:
```require 'cfndsl'

CloudFormation do
  EC2_EIP('eip') do
    Domain 'vpc'
  end

  allocation_id = "${eip.AllocationId}"

  Output('output') do
    Value FnSub(allocation_id)
    Export 'eip-allocation-id'
  end
end
```

Expected output:
```
---
AWSTemplateFormatVersion: '2010-09-09'
Resources:
  eip:
    Properties:
      Domain: vpc
    Type: AWS::EC2::EIP
Outputs:
  output:
    Value:
      Fn::Sub: "${eip.AllocationId}"
    Export:
      Name: eip-allocation-id
```

Referring to the resource itself, rather than one of its attributes, using the shorthand notation works fine (ie, `${eip}` in the reproduction case -- but, obviously returns different data), as does using an arbitrary variable name in the template string and supplying the substitution using FnSub's second argument consisting of a hash of variable name/values.

The reproduction case template compiles successfully with cfndsl v0.17.5 (note, requires an old resource_specification.json file due to other-since-fixed problems... but those are not relevant to this issue).

Template does not compile with cfndsl v1.0.6.  Tested each version from v1.0.5 back to v1.0.0 with the same failing result.

**Comment by lwoggardner** [comment]
I will have a look at this. Validation of references is tighter in 1.0
