### ISSUE TITLE
SecurityGroupIngress is always an array - 1.1.1

### ISSUE THREAD

**Issue by zsyk899** [cfndsl/cfndsl#460]
Hi, 

We use the following code snippet to create a security group
```
  EC2_SecurityGroup("SecurityGroup") do
    GroupDescription "Security Group"
    VpcId Ref("VpcId")
    SecurityGroupIngress FnFindInMap("SecurityGroupInbound", Ref("Environment"), "allowedIPs")
  end
```
but the generated CF template looks like:
```
      SecurityGroupIngress:
      - Fn::FindInMap:
        - ElbSecurityGroupInbound
        - Ref: Environment
        - allowedIPs
```
The input of SecurityGroupIngress becomes a nested list.

The expected template should be
```
      SecurityGroupIngress:
        Fn::FindInMap:
        - ElbSecurityGroupInbound
        - Ref: Environment
        - allowedIPs
```

I noticed similar issue was raised previously at https://github.com/cfndsl/cfndsl/issues/442, but I couldn't find a way to make the `SecurityGroupIngress` plural. 

Can I please have some helps on this?

Thanks
Kevin

**Comment by lwoggardner** [comment]
SecurityGroupIngress and SecurityGroupEgress are special case plural because its singlular name is the same as its plural name.

The behaviour of these is one of the inconsistencies resolved in 1.x

To use a non array value for such a property you can use the #Property method.

```ruby
  EC2_SecurityGroup("SecurityGroup") do
    GroupDescription "Security Group"
    VpcId Ref("VpcId")
    Property('SecurityGroupIngress',FnFindInMap("SecurityGroupInbound", Ref("Environment"), "allowedIPs")
  end
```

**Comment by zsyk899** [comment]
Thank you very much! It did the trick.
