### ISSUE TITLE
Freeze specifications version

### ISSUE THREAD

**Issue by gdlx** [cfndsl/cfndsl#466]
Each time I'm looking if cloud formation specifications have been updated (and each time they have been), I need to find which is the latest version working with CfnDsl (by looking at latest commits or groping for it).

I think it is useless to make CfnDsl update to the latest version by default knowing it ~ never works with the latest version.

At the time of writing this, the latest version is 21.0.0 but the last compatible one is 16.2.0.

Wouldn't it be better to freeze the latest compatible version and make CfnDsl download it by default ? (specifying a version would still be useful to test & fix newest versions).

Thanks !

**Comment by gergnz** [comment]
Hi @gdlx , thanks for reporting this. We welcome pull requests to resolve these issues, but I have thought about an automated test process that runs regularly to pull the latest specification down and test that it works.

Let me take a look at both options and see how we go.

**Comment by gdlx** [comment]
Your solution sounds way better than freezing the version so I'll close it. I've already frozen the version on my project so having a fast way to know the last compatible version would fit my needs.
