### ISSUE TITLE
Unintended side effectos of PR #64 - Need better error messages for ambiguous resources.

### ISSUE THREAD

**Issue by howech** [cfndsl/cfndsl#68]
A recent change added support for OpsWorks, which defines both a Stack and and Instance resource type. This makes it so that Instance and Stack are no longer valid top level resource names. You have to use CloudFormation_Stack or EC2_Instance or the OpsWorks _ flavors explicitly.

The trouble with this is that many existing scripts out there will now fail in cryptic ways.

The solution is to ensure that ambiguous resource definitions emit explicit error messages

**Comment by lwoggardner** [comment]
This was fixed in 1.x which requires explicit top level names
