### ISSUE TITLE
[feature] a File() helper than can interpolate references for UserData scripts

### ISSUE THREAD

**Issue by rprieto** [cfndsl/cfndsl#95]
Hi,

I think it's quite common to have to write `userdata` scripts that contain CloudFormation references. They usually look something like this:

``` json
"UserData":{
  "Fn::Base64":{
    "Fn::Join":[
      "",
      [
        "#!/bin/bash -vx\n",
        "/opt/aws/bin/cfn-init -s ", { "Ref":"AWS::StackId" }, " -r LaunchConfig --region ", { "Ref":"AWS::Region" }, "\n",
        "sh /tmp/setup.sh\n",
        "sleep 5\n",
        "/opt/aws/bin/cfn-signal -e $? ", " --stack ", { "Ref":"AWS::StackName" }, " --resource ServiceFleet ", " --region ", { "Ref":"AWS::Region" },
      ]
    ]
  }
}
```

It would be great if the DSL allowed us to write _`userdata.sh`_ (with bonus syntax highlighting):

``` bash
#!/bin/bash -vx
/opt/aws/bin/cfn-init -s {{AWS::StackId}} -r LaunchConfig --region {{AWS::Region}}
sh /tmp/setup.sh
sleep 5
/opt/aws/bin/cfn-signal -e $? --stack {{AWS::StackName}} --resource ServiceFleet --region {{AWS::Region}}
```

and then:

``` ruby
UserData FnBase64(File("userdata.sh"))
```

Is that something you `cfnsdl` already supports that I missed, or a feature you think could be useful? Note the example above would only handle simple `Ref`s, which would already be useful. I can't think of a nice syntax to support the full gamut of operations like `FindInMap`, etc...

Thanks

**Comment by stevenjack** [comment]
@rprieto I know the pain you feel it's a real pain creating the userdata scripts line-by-line when you need to interpolate stack params inside the file.

Currently it's not something cfndsl supports natively. I think as you mentioned in your last comment, it's not that being able to turn a file into the string type `cfndsl` expects would be difficult but more how we express all the different types such as `FindInMap` in the file you'd like to parse being the harder part.

Let me have a think about this, there might be a more elegant way around it. @howech any thoughts?

**Comment by rprieto** [comment]
Thanks for getting back to me, keen to see how the conversation progresses!

**Comment by howech** [comment]
Cfndsl adds a fake function called "FnFormat" that turns interpolates strings with %{tag} style tags into Fn::Join and Fn::Ref functions as required. For instance FnFormat ( "Hello %{world}") would turn into the cfn jason {"Fn::Join":["", ["Hello ", {"Ref": "world"}]}. Between that an ruby ' File.read call, you can probably get a long way towards what you are looking for.

**Comment by herebebogans** [comment]
The addition of FnSub() now makes this pretty simple - variables in template get interpolated via ${} tags at CF runtime. So for your example.

cfndsl template

> USER_DATA=File.read('userdata.sh')
> .....snipped...
> UserData FnBase64(FnSub(USER_DATA))

userdata.sh

> #!/bin/bash -vx
> /opt/aws/bin/cfn-init -s ${AWS::StackId} -r LaunchConfig --region ${AWS::Region}
> sh /tmp/setup.sh
> sleep 5
> /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackName} --resource ServiceFleet --region ${AWS::Region}

**Comment by cmaxwellau** [comment]
Surely this can be closed now
